### ISSUE TITLE
Consumer affected by merchant rate limiting

### ISSUE THREAD

**Issue by CarstenWalther** [hpi-epic/pricewars#30]
Currently, the consumer waits 30 seconds when being limited.

**Comment by Bouncner** [comment]
What? Seriously?

**Comment by CarstenWalther** [comment]
Yes I often get  a HTTP 429 Response

**Comment by Bouncner** [comment]
Is this related to your open consumer PR?

**Comment by CarstenWalther** [comment]
No, the PR is some clean up and does not fixes this problem.
However, I removed the consumer rate limiting in this commit: https://github.com/hpi-epic/pricewars-marketplace/commit/ed07ea0a67583b3ffc8efe69bf1e32a9bae9224a
